// D1Database is a global ambient type from worker-configuration.d.ts
// (generated by `wrangler types`) — no import needed.
//
// Minimal schema for the tables the Connector's own routes touch
// (wp-bridge.ts, and orders.ts's read side). Mirrors migrations/6.sql and
// migrations/7.sql exactly — kept here rather than replaying the full
// migration chain so these tests stay fast and independent of unrelated
// tables (the brand vault, giving, coupons, etc.) that migrations/2.sql and
// others seed. If those two migration files change, update this to match.
export async function applyConnectorSchema(db: D1Database) {
  // D1's exec() splits on newlines (it expects one statement per line), so
  // a pretty-printed multi-line CREATE TABLE has to go through
  // prepare().run() instead — exec() would choke on it mid-statement.
  await db
    .prepare(
      `CREATE TABLE IF NOT EXISTS wp_bridge_events (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        event_id TEXT NOT NULL UNIQUE,
        event_type TEXT NOT NULL,
        schema_version TEXT NOT NULL DEFAULT '1.0',
        occurred_at TEXT NOT NULL,
        payload_json TEXT NOT NULL,
        received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )`
    )
    .run()

  await db
    .prepare(
      `CREATE TABLE IF NOT EXISTS orders (
        order_id TEXT PRIMARY KEY,
        source TEXT NOT NULL DEFAULT 'woocommerce',
        external_id TEXT,
        customer_email TEXT,
        total_zar INTEGER,
        currency TEXT DEFAULT 'ZAR',
        payment_status TEXT NOT NULL DEFAULT 'pending',
        status TEXT NOT NULL DEFAULT 'pending',
        wc_status_raw TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )`
    )
    .run()
}

export async function signBody(secret: string, body: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  )
  const mac = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(body))
  return [...new Uint8Array(mac)].map((b) => b.toString(16).padStart(2, '0')).join('')
}
