
-- Seed FAA brands
INSERT INTO brands (name, system, tier, category, description, emoji, fee, royalty, is_active, created_at, updated_at) VALUES
('Playing with the Seed™', 'faa', 'sovereign', 'Core Governance', 'Master licensing and IP guardian framework', '🌱', '25000 ECR', '18.0%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('FAA™ Ecosystem', 'faa', 'sovereign', 'Core Governance', 'Central governance and distribution node', '🏛️', '24500 ECR', '17.5%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Atom-Level Compliance™', 'faa', 'sovereign', 'Compliance Tech', 'Molecular-grade regulatory tracking system', '⚛️', '23000 ECR', '16.8%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Fruitful Crate Dance™', 'faa', 'dynastic', 'Media & Culture', 'World-first streaming event infrastructure', '💃', '12500 ECR', '13.2%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('The Donkey & Rocket™', 'faa', 'dynastic', 'Media & Culture', 'Metaphorical narrative media engine', '🚀', '11800 ECR', '12.8%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Inline Compliance™', 'faa', 'dynastic', 'Compliance Tech', 'Real-time regulatory synchronization', '✅', '10900 ECR', '12.5%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Global Crate Network', 'faa', 'operational', 'Technology', 'Physical trade route management system', '🌐', '6200 ECR', '11.2%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Baobab Media', 'faa', 'operational', 'Media & Culture', 'Legacy-focused content production', '🌳', '5800 ECR', '10.9%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('PulseTrade™', 'faa', 'sovereign', 'Technology', '9-second heartbeat synchronization protocol', '💓', '22000 ECR', '16.5%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('BareCart™', 'faa', 'dynastic', 'Technology', 'Vortex grain factory - zero waste commerce', '🛒', '11200 ECR', '12.4%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ClaimRoot™', 'faa', 'sovereign', 'Technology', 'Immutable brand claims and verification', '🔐', '21500 ECR', '16.2%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('VaultMesh™', 'faa', 'operational', 'Technology', 'Open source DNA distribution network', '🕸️', '6000 ECR', '10.8%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('40D Store', 'faa', 'dynastic', 'Technology', 'Multi-dimensional data storage system', '📦', '10800 ECR', '12.1%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CrateLogic™', 'faa', 'operational', 'Technology', 'Container protocol and movement tracking', '📊', '5900 ECR', '10.7%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SwimJacket™', 'faa', 'dynastic', 'Technology', 'Seed protection - no seed drowned protocol', '🦺', '11500 ECR', '12.6%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('TreatyHook™', 'faa', 'sovereign', 'Core Governance', 'OMNI-4321 legal framework enforcement', '⚖️', '24000 ECR', '17.2%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Gorilla Codex', 'faa', 'sovereign', 'Core Governance', 'Self-destruct revenue node protection', '🦍', '23500 ECR', '16.9%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Banimals™', 'faa', 'dynastic', 'Animal Welfare', 'Animal welfare - 15% care loop system', '🐾', '12000 ECR', '13.0%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Digital Great Wall', 'faa', 'sovereign', 'Technology', '永不崩塌 - Infrastructure security protocol', '🏯', '22500 ECR', '16.7%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Shanana™', 'faa', 'operational', 'Technology', 'Sub-9s routing and passive ventilation', '⚡', '6100 ECR', '11.0%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Banimal Store', 'faa', 'market', 'Technology', 'E-commerce integration platform', '🏪', '3800 ECR', '8.5%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hotstack Nexus', 'faa', 'dynastic', 'Technology', 'Central orchestration framework', '🎯', '11000 ECR', '12.3%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Oracle Bone Logs', 'faa', 'sovereign', 'Technology', 'Immutable ledger - ancient meets modern', '📜', '21000 ECR', '16.0%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('PayPal VIP Live', 'faa', 'operational', 'Technology', 'Checkout integration - K65YZZXSGZ7U', '💳', '5700 ECR', '10.5%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Elephant Memory™', 'faa', 'sovereign', 'Technology', '21M files infinite storage - never forgotten', '🐘', '23800 ECR', '17.0%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Noodle Nexus', 'faa', 'dynastic', 'Technology', 'Central system orchestration', '🍜', '11300 ECR', '12.4%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ant Network', 'faa', 'operational', 'Technology', '1000-year emergence architecture', '🐜', '6050 ECR', '10.8%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Termite Climate', 'faa', 'operational', 'Technology', 'Passive ventilation - 30.5°C precision', '🏗️', '5950 ECR', '10.7%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vortex Grain Path', 'faa', 'dynastic', 'Technology', 'Grain counting - zero waste tracking', '🌀', '10700 ECR', '12.0%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ceramic Spoon Vortex', 'faa', 'sovereign', 'Core Governance', '瓷勺旋渦 - Ancient wisdom protocol', '🥄', '24200 ECR', '17.4%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Seed HSOMNI9000 brands
INSERT INTO brands (name, system, tier, category, description, emoji, fee, royalty, is_active, created_at, updated_at) VALUES
('HSOMNI∞ONE™', 'hsomni', 'sovereign', 'Core Governance', 'Infinite governance protocol - main framework', '♾️', '24800 ECR', '17.8%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('AI Logic Grid', 'hsomni', 'dynastic', 'AI & Logic', 'Machine learning infrastructure platform', '🧠', '11400 ECR', '12.5%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Health Hygiene Pro', 'hsomni', 'operational', 'Health & Hygiene', 'Healthcare compliance and tracking', '🏥', '6300 ECR', '11.1%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('LogiPack Global', 'hsomni', 'operational', 'Logistics & Packaging', 'International logistics coordination', '📦', '6150 ECR', '10.9%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('InfraHouse Build', 'hsomni', 'dynastic', 'Housing & Infrastructure', 'Construction and infrastructure management', '🏗️', '10700 ECR', '12.2%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('FoodSoil Organic', 'hsomni', 'operational', 'Food, Soil & Farming', 'Organic farming certification system', '🌾', '5950 ECR', '10.8%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('EduIP Academy', 'hsomni', 'dynastic', 'Education & IP', 'Educational intellectual property platform', '🎓', '11100 ECR', '12.4%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MotionMedia Sonic', 'hsomni', 'operational', 'Motion, Media & Sonic', 'Multimedia production suite', '🎬', '6050 ECR', '10.7%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Webless Node Tech', 'hsomni', 'dynastic', 'Webless Tech & Nodes', 'Decentralized node infrastructure', '🔗', '10900 ECR', '12.3%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ProServices Elite', 'hsomni', 'operational', 'Professional Services', 'B2B professional services platform', '💼', '6200 ECR', '11.0%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('HSOMNI Compliance', 'hsomni', 'sovereign', 'Compliance Tech', 'Automated regulatory compliance engine', '✅', '22800 ECR', '16.6%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Neural Grid AI', 'hsomni', 'dynastic', 'AI & Logic', 'Neural network processing framework', '🤖', '11600 ECR', '12.7%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MedTech Solutions', 'hsomni', 'operational', 'Health & Hygiene', 'Medical technology integration', '⚕️', '6100 ECR', '10.9%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SmartPack Logistics', 'hsomni', 'market', 'Logistics & Packaging', 'Smart packaging solutions', '📮', '3650 ECR', '8.4%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('EcoHouse Green', 'hsomni', 'operational', 'Housing & Infrastructure', 'Sustainable housing platform', '🏡', '5850 ECR', '10.6%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('AgriTech Farm', 'hsomni', 'dynastic', 'Food, Soil & Farming', 'Agricultural technology suite', '🚜', '10600 ECR', '12.1%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Learn & Protect IP', 'hsomni', 'operational', 'Education & IP', 'IP protection for educational content', '📚', '6000 ECR', '10.8%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('StreamFlow Media', 'hsomni', 'dynastic', 'Motion, Media & Sonic', 'Live streaming infrastructure', '📡', '11300 ECR', '12.5%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NodeMesh Network', 'hsomni', 'operational', 'Webless Tech & Nodes', 'Mesh network protocol', '🌐', '6250 ECR', '11.1%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Consult Pro Global', 'hsomni', 'market', 'Professional Services', 'Global consulting platform', '🌍', '3550 ECR', '8.3%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('HSOMNI Vault', 'hsomni', 'sovereign', 'Technology', 'Secure data vault infrastructure', '🔒', '23200 ECR', '16.8%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Quantum AI Logic', 'hsomni', 'sovereign', 'AI & Logic', 'Quantum computing AI framework', '⚡', '24200 ECR', '17.3%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('HealthChain Block', 'hsomni', 'dynastic', 'Health & Hygiene', 'Blockchain health records', '⛓️', '10800 ECR', '12.2%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('GlobalShip Track', 'hsomni', 'operational', 'Logistics & Packaging', 'Global shipment tracking', '🚢', '6050 ECR', '10.8%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SmartCity Infra', 'hsomni', 'dynastic', 'Housing & Infrastructure', 'Smart city infrastructure', '🌆', '11200 ECR', '12.4%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Seed Seedwave Premium brands
INSERT INTO brands (name, system, tier, category, description, emoji, fee, royalty, is_active, created_at, updated_at) VALUES
('Seedwave Elite', 'seedwave', 'sovereign', 'Core Governance', 'Premium verified brand certification', '⭐', '25500 ECR', '18.5%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Seedwave Global', 'seedwave', 'sovereign', 'Technology', 'Global deployment verification system', '🌍', '24900 ECR', '18.2%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Seedwave Trust', 'seedwave', 'sovereign', 'Compliance Tech', 'Trust and verification framework', '🛡️', '24300 ECR', '17.9%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Seedwave Commerce', 'seedwave', 'dynastic', 'Technology', 'E-commerce premium integration', '💳', '12800 ECR', '13.5%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Seedwave Analytics', 'seedwave', 'dynastic', 'Technology', 'Advanced analytics platform', '📊', '12500 ECR', '13.3%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Seedwave Security', 'seedwave', 'sovereign', 'Technology', 'Enterprise security framework', '🔐', '25000 ECR', '18.0%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Seedwave AI', 'seedwave', 'dynastic', 'AI & Logic', 'AI-powered brand intelligence', '🤖', '12200 ECR', '13.1%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Seedwave Mobile', 'seedwave', 'operational', 'Technology', 'Mobile-first platform suite', '📱', '6500 ECR', '11.5%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Seedwave Cloud', 'seedwave', 'dynastic', 'Technology', 'Cloud infrastructure platform', '☁️', '12600 ECR', '13.4%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Seedwave Insight', 'seedwave', 'operational', 'Technology', 'Business intelligence dashboard', '💡', '6400 ECR', '11.4%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Seedwave Premium Plus', 'seedwave', 'sovereign', 'Core Governance', 'Highest tier premium access', '👑', '26000 ECR', '18.8%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Seedwave Verify', 'seedwave', 'dynastic', 'Compliance Tech', 'Brand verification services', '✓', '11900 ECR', '12.9%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Seedwave Partner', 'seedwave', 'operational', 'Technology', 'Partnership management platform', '🤝', '6300 ECR', '11.3%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Seedwave Growth', 'seedwave', 'dynastic', 'Technology', 'Growth acceleration platform', '📈', '12100 ECR', '13.0%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Seedwave Scale', 'seedwave', 'operational', 'Technology', 'Scalability infrastructure', '⚙️', '6250 ECR', '11.2%', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
